# Generated by Django 4.2.3 on 2023-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemtnumber',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
